#!/bin/sh
set -e

cp /home/"$SUDO_USER"/gh-pages-nginx/etc/nginx/conf.d/*.conf /etc/nginx/conf.d/

nginx -t
systemctl reload nginx

certbot --nginx -n --agree-tos -m email@example.com --redirect -d example.com,www.example.com
